name = "linkden-api"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[vars]
CORS_ORIGIN = "https://linkden-web.mrdemonwolf.workers.dev"
APP_URL = "https://linkden-api.mrdemonwolf.workers.dev"
CF_ACCESS_TEAM_DOMAIN = "mrdemonwolf"

[[d1_databases]]
binding = "DB"
database_name = "linkden-db"
database_id = "8f2efc27-b2f4-4139-b807-fdab7adeaee4"
